import unittest
from Main import *


# If test failed try to run it again and again until it passes.
# The output of the program may differ from one to another because some json elements can appear in a different order

class TestParser(unittest.TestCase):
    def setUp(self):
        pass

    def test_parser(self):
        result = main("test.txt", None)
        final_result = "'" + result + "'"

        self.assertEqual(final_result, repr('{"File_input": [{"val": "\n", "type": "NAME"}, {"Stmt": [{"Simple_stmt": '
                                            '[{"Small_stmt": [{"Import_stmt": [{"Import_name": [{"val": "import", '
                                            '"type": "AS"}, {"Dotted_as_names": [{"Dotted_as_name": [{"Dotted_name": ['
                                            '{"val": "sys", "type": "STRING_LITERAL"}]}]}]}]}]}]}, {"val": "\n", '
                                            '"type": "NAME"}]}]}, {"Stmt": [{"Compound_stmt": [{"Funcdef": [{"val": '
                                            '"def", "type": "RETURN"}, {"val": "max", "type": "STRING_LITERAL"}, '
                                            '{"Parameters": [{"val": "(", "type": "CLOSE_PAREN"}, {"Typedargslist": [{'
                                            '"Tfpdef": [{"val": "a", "type": "STRING_LITERAL"}]}, {"val": ",", '
                                            '"type": "COLON"}, {"Tfpdef": [{"val": "b", "type": "STRING_LITERAL"}]}]}, '
                                            '{"val": ")", "type": "COMMA"}]}, {"val": ":", "type": "SEMI_COLON"}, '
                                            '{"Suite": [{"val": "\n", "type": "NAME"}, {"val": "    ", '
                                            '"type": "LONG_STRING"}, {"Stmt": [{"Compound_stmt": [{"If_stmt": [{"val": '
                                            '"if", "type": "ELIF"}, {"Test": [{"Or_test": [{"And_test": [{"Not_test": '
                                            '[{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{"Shift_expr": [{'
                                            '"Arith_expr": [{"Term": [{"Factor": [{"Power": [{"Atom_expr": [{"Atom": ['
                                            '{"val": "a", "type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}, {"Comp_op": ['
                                            '{"val": ">", "type": "EQUALS"}]}, {"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "b", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ":", '
                                            '"type": "SEMI_COLON"}, {"Suite": [{"val": "\n", "type": "NAME"}, '
                                            '{"val": "        ", "type": "LONG_STRING"}, {"Stmt": [{"Simple_stmt": [{'
                                            '"Small_stmt": [{"Flow_stmt": [{"Return_stmt": [{"val": "return", '
                                            '"type": "RAISE"}, {"Testlist": [{"Test": [{"Or_test": [{"And_test": [{'
                                            '"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "a", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, '
                                            '{"val": "\n", "type": "NAME"}]}]}, {"val": " ", '
                                            '"type": "LONG_STRING_ITEM"}]}, {"val": "else", "type": "WHILE"}, '
                                            '{"val": ":", "type": "SEMI_COLON"}, {"Suite": [{"val": "\n", '
                                            '"type": "NAME"}, {"val": "        ", "type": "LONG_STRING"}, {"Stmt": [{'
                                            '"Simple_stmt": [{"Small_stmt": [{"Flow_stmt": [{"Return_stmt": [{"val": '
                                            '"return", "type": "RAISE"}, {"Testlist": [{"Test": [{"Or_test": [{'
                                            '"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{'
                                            '"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{'
                                            '"Power": [{"Atom_expr": [{"Atom": [{"val": "b", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, '
                                            '{"val": "\n", "type": "NAME"}]}]}, {"val": "\n", '
                                            '"type": "LONG_STRING_ITEM"}]}]}]}]}, {"val": "\n", '
                                            '"type": "LONG_STRING_ITEM"}]}]}]}]}, {"Stmt": [{"Compound_stmt": [{'
                                            '"For_stmt": [{"val": "for", "type": "IN"}, {"Exprlist": [{"Expr": [{'
                                            '"Xor_expr": [{"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{'
                                            '"Factor": [{"Power": [{"Atom_expr": [{"Atom": [{"val": "line", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}, {"val": "in", '
                                            '"type": "TRY"}, {"Testlist": [{"Test": [{"Or_test": [{"And_test": [{'
                                            '"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "sys", "type": "STRING_LITERAL"}]}, '
                                            '{"Trailer": [{"val": ".", "type": "ELLIPSIS"}, {"val": "stdin", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ":", '
                                            '"type": "SEMI_COLON"}, {"Suite": [{"val": "\n", "type": "NAME"}, '
                                            '{"val": "    ", "type": "LONG_STRING"}, {"Stmt": [{"Simple_stmt": [{'
                                            '"Small_stmt": [{"Expr_stmt": [{"Testlist_star_expr": [{"Test": [{'
                                            '"Or_test": [{"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{'
                                            '"Xor_expr": [{"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{'
                                            '"Factor": [{"Power": [{"Atom_expr": [{"Atom": [{"val": "print", '
                                            '"type": "STRING_LITERAL"}]}, {"Trailer": [{"val": "(", '
                                            '"type": "CLOSE_PAREN"}, {"Arglist": [{"Argument": [{"Test": [{"Or_test": '
                                            '[{"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{'
                                            '"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{'
                                            '"Power": [{"Atom_expr": [{"Atom": [{"val": "sum", '
                                            '"type": "STRING_LITERAL"}]}, {"Trailer": [{"val": "(", '
                                            '"type": "CLOSE_PAREN"}, {"Arglist": [{"Argument": [{"Test": [{"Or_test": '
                                            '[{"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{'
                                            '"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{'
                                            '"Power": [{"Atom_expr": [{"Atom": [{"val": "map", '
                                            '"type": "STRING_LITERAL"}]}, {"Trailer": [{"val": "(", '
                                            '"type": "CLOSE_PAREN"}, {"Arglist": [{"Argument": [{"Test": [{"Or_test": '
                                            '[{"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{'
                                            '"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{'
                                            '"Power": [{"Atom_expr": [{"Atom": [{"val": "int", '
                                            '"type": "STRING_LITERAL"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ",", '
                                            '"type": "COLON"}, {"Argument": [{"Test": [{"Or_test": [{"And_test": [{'
                                            '"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "line", "type": "STRING_LITERAL"}]}, '
                                            '{"Trailer": [{"val": ".", "type": "ELLIPSIS"}, {"val": "split", '
                                            '"type": "STRING_LITERAL"}]}, {"Trailer": [{"val": "(", '
                                            '"type": "CLOSE_PAREN"}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": "\n", '
                                            '"type": "NAME"}]}]}, {"Stmt": [{"Simple_stmt": [{"Small_stmt": [{'
                                            '"Expr_stmt": [{"Testlist_star_expr": [{"Test": [{"Or_test": [{"And_test": '
                                            '[{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "print", "type": "STRING_LITERAL"}]}, '
                                            '{"Trailer": [{"val": "(", "type": "CLOSE_PAREN"}, {"Arglist": [{'
                                            '"Argument": [{"Test": [{"Or_test": [{"And_test": [{"Not_test": [{'
                                            '"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{"Shift_expr": [{'
                                            '"Arith_expr": [{"Term": [{"Factor": [{"Power": [{"Atom_expr": [{"Atom": ['
                                            '{"val": "max", "type": "STRING_LITERAL"}]}, {"Trailer": [{"val": "(", '
                                            '"type": "CLOSE_PAREN"}, {"Arglist": [{"Argument": [{"Test": [{"Or_test": '
                                            '[{"And_test": [{"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{'
                                            '"And_expr": [{"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{'
                                            '"Power": [{"Atom_expr": [{"Atom": [{"val": "12", '
                                            '"type": "INTEGER"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ",", '
                                            '"type": "COLON"}, {"Argument": [{"Test": [{"Or_test": [{"And_test": [{'
                                            '"Not_test": [{"Comparison": [{"Expr": [{"Xor_expr": [{"And_expr": [{'
                                            '"Shift_expr": [{"Arith_expr": [{"Term": [{"Factor": [{"Power": [{'
                                            '"Atom_expr": [{"Atom": [{"val": "14", '
                                            '"type": "INTEGER"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": ")", '
                                            '"type": "COMMA"}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}, {"val": "\n", '
                                            '"type": "NAME"}]}]}, {"val": "\n", "type": "LONG_STRING_ITEM"}]}]}]}]}, '
                                            '{"val": "<EOF>", "type": "ID_CONTINUE"}]}'))


if __name__ == '__main__':
    unittest.main()
